version: "3"
services:
  hub:
    image: selenium/hub
  chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  bdd:
    image: jagadeeshv20/selenium-docker-bdd:latest
    depends_on:
      - chrome
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - CUCUMBER_OPTIONS=classpath:features
    volumes:
      - ./output:/usr/share/bdd/target/cucumber-reports